### ISSUE TITLE
IMPORTANT: Refactor logic for connect use case

### ISSUE THREAD

**Issue by HaochongYANG** [KellyQiuu/195Final#62]
<img width="1624" alt="image" src="https://github.com/KellyQiuu/195Final/assets/105600012/232a66e9-5c3c-4d42-af37-3e1f719c7eb3">

**Comment by KellyQiuu** [comment]
Hi Bodddy, please be noted that there is a class in use_case folder which is called UserSecession. Take a look. YOu can freely import that and use its .getCurrentUser() to get sender information.
