### ISSUE TITLE
IMPORTANT: Home Page refactor, need to show label texts and change colors.

### ISSUE THREAD

**Issue by HaochongYANG** [KellyQiuu/195Final#63]
<img width="912" alt="image" src="https://github.com/KellyQiuu/195Final/assets/105600012/f5a4d1fd-5337-40ad-9699-377eacb59841">

**Comment by Escalloniales** [comment]
The issue is due to how each system (macOS/Windows) handles the look of Java Swing components. The background colour is already set in black. Change should be made after we decide whose computer will be used in the presentation.
